"""Stress harness: runs the scenario catalog, a flakiness study, and a determinism check, and keeps the evidence.

Writes evidence/stress/{runs/, stability/, SUMMARY.md, summary.json}. No LLM involved.

    PYTHONPATH=src:. .venv/bin/python scripts/stress.py [--repeats 20]
"""

from __future__ import annotations

import argparse
import json
import shutil
import statistics
import sys
import time
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT / "src"), str(ROOT)]

from mockbank import data  # noqa: E402
from mockbank.app import MockBankServer  # noqa: E402
from cua.evals.scenarios import M1001, SAVINGS, SCENARIOS, Scenario, run_scenario  # noqa: E402

OUT = ROOT / "evidence" / "stress"
CANARIES = ([m.ssn for m in data.seed_members().values()] + [m.dob for m in data.seed_members().values()]
            + list(data.seed_members()) + [data.OPERATOR_PASSWORD, "jane.doe@bank.example", "2,450.17", "2450.17"]
            + [m.name for m in data.seed_members().values()])


def code_of(result) -> str:
    if result.bucket == "ESCALATED":
        if result.business_code:
            return result.business_code.value
        return "with outputs" if result.outputs else "operator took over"
    c = getattr(result, "reason", None) or getattr(result, "code", None)
    return getattr(c, "value", c) or ""


def matrix(base_url: str) -> list[dict]:
    rows = []
    for sc in SCENARIOS:
        t0 = time.time()
        report, problems = run_scenario(sc, base_url, OUT / "runs")
        rows.append({"id": sc.id, "category": sc.category, "title": sc.title, "capability": sc.capability,
                     "expected": f"{sc.bucket} {sc.code or ''}".strip(),
                     "actual": f"{report.result.bucket} {code_of(report.result)}".strip(),
                     "recoveries": [r.kind for r in report.result.recoveries],
                     "handoffs": len(getattr(report.result, "handoffs", []) or []),
                     "ui_actions": report.ui_actions, "seconds": round(time.time() - t0, 1),
                     "pass": not problems, "problems": problems, "shows": sc.shows, "run": f"runs/{report.run_id}"})
        print(f"{sc.id} {'PASS' if not problems else 'FAIL'} {rows[-1]['actual']:<40} {sc.title}")
    return rows


def stability(base_url: str, repeats: int) -> dict:
    """Flaky backend: 30% of account-detail requests fail. How often does the retry budget absorb it?"""
    buckets, recoveries, secs = Counter(), Counter(), []
    for i in range(repeats):
        sc = Scenario(f"S{i + 1:02d}", "stability", "Flaky backend (30% HTTP 500)", SAVINGS, M1001, "SUCCESS",
                      faults={"flaky_rate": 0.3, "flaky_seed": 1000 + i})
        t0 = time.time()
        report, _ = run_scenario(sc, base_url, OUT / "stability")
        secs.append(time.time() - t0)
        buckets[f"{report.result.bucket} {code_of(report.result)}".strip()] += 1
        recoveries.update(r.kind for r in report.result.recoveries)
    ok = buckets.get("SUCCESS", 0)
    return {"repeats": repeats, "flaky_rate": 0.3, "success_rate": round(ok / repeats, 3), "buckets": dict(buckets),
            "recoveries": dict(recoveries), "p50_s": round(statistics.median(secs), 2),
            "max_s": round(max(secs), 2)}


def determinism(base_url: str, repeats: int) -> dict:
    traces, secs = set(), []
    for i in range(repeats):
        sc = Scenario(f"D{i + 1:02d}", "determinism", "Baseline repeat", SAVINGS, M1001, "SUCCESS")
        t0 = time.time()
        report, problems = run_scenario(sc, base_url, OUT / "stability")
        secs.append(time.time() - t0)
        events = [json.loads(x) for x in (OUT / "stability" / report.run_id / "events.jsonl").read_text().splitlines()]
        traces.add((report.result.bucket, tuple(report.steps_executed),
                    tuple((e["step"], e["candidate"]) for e in events if e["kind"] == "resolved"), not problems))
    return {"repeats": repeats, "distinct_traces": len(traces), "p50_s": round(statistics.median(secs), 2),
            "max_s": round(max(secs), 2)}


def pii_scan() -> list[str]:
    hits = []
    for p in OUT.rglob("*"):
        if p.is_file() and p.suffix in (".json", ".jsonl", ".txt", ".md"):
            text = p.read_text()
            hits += [f"{p.relative_to(ROOT)}: {c}" for c in CANARIES if c in text]
    return hits


def write_summary(rows: list[dict], stab: dict, det: dict, leaks: list[str]) -> None:
    passed = sum(r["pass"] for r in rows)
    by_cat = Counter(r["category"] for r in rows)
    lines = [
        "# Stress Test Evidence", "",
        "Generated by `scripts/stress.py`. Each scenario injects a browser or backend condition into the mock app, "
        "replays a golden artifact in a fresh browser session (no LLM), and checks that the result contract reports "
        "exactly the expected outcome. Every run's structured log (`events.jsonl`), result (`result.json`), and, on "
        "failure or handoff, a masked screenshot plus redacted page text are kept under `runs/`.", "",
        f"**Matrix: {passed}/{len(rows)} scenarios matched their expected outcome.** "
        f"Categories: {', '.join(f'{k} {v}' for k, v in by_cat.items())}.", "",
        "| ID | Category | Condition | Expected | Actual | Recoveries | Handoffs | Pass | Evidence |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        rec = ", ".join(f"{k} x{v}" if v > 1 else k for k, v in Counter(r["recoveries"]).items()) or "none"
        lines.append(f"| {r['id']} | {r['category']} | {r['title']} | {r['expected']} | {r['actual']} | {rec} | "
                     f"{r['handoffs']} | {'yes' if r['pass'] else 'NO: ' + '; '.join(r['problems'])} | "
                     f"[{r['run'].split('/')[-1]}]({r['run']}/) |")
    lines += ["", "## What each scenario proves", ""]
    lines += [f"- **{r['id']}** {r['title']}: {r['shows']}" for r in rows if r["shows"]]
    lines += [
        "", "## Flakiness study", "",
        f"Backend fails {int(stab['flaky_rate'] * 100)}% of account-detail requests at random (seeded per run). "
        f"Over {stab['repeats']} fresh runs, the retry budget produced **{stab['success_rate']:.0%} SUCCESS**. "
        f"Outcomes: {stab['buckets']}. Recoveries used: {stab['recoveries']}. "
        f"Median {stab['p50_s']}s, worst {stab['max_s']}s. Runs are in `stability/`.", "",
        "## Determinism check", "",
        f"The clean baseline replayed {det['repeats']} times produced **{det['distinct_traces']} distinct trace(s)** "
        f"(bucket, steps executed, and which locator candidate resolved each step). "
        f"Median {det['p50_s']}s, worst {det['max_s']}s.", "",
        "## Data handling", "",
        f"PII and secret scan over everything in `evidence/stress/` (seeded SSNs, DOBs, full member ids, the operator "
        f"password, an email echoed by X36): **{'clean' if not leaks else f'{len(leaks)} hits'}**.",
        "Sensitive outputs (the balance) are masked in every `result.json` on disk while the caller still receives "
        "them. Screenshots mask SSN, date, email, and account-number patterns and password fields.",
    ]
    if leaks:
        lines += [f"- {h}" for h in leaks]
    (OUT / "SUMMARY.md").write_text("\n".join(lines) + "\n")
    (OUT / "summary.json").write_text(json.dumps({"matrix": rows, "stability": stab, "determinism": det,
                                                  "pii_hits": leaks}, indent=2))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repeats", type=int, default=20)
    args = ap.parse_args()
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True)
    srv = MockBankServer().start()
    try:
        rows = matrix(srv.base_url)
        stab = stability(srv.base_url, args.repeats)
        det = determinism(srv.base_url, max(5, args.repeats // 2))
    finally:
        srv.stop()
    leaks = pii_scan()
    write_summary(rows, stab, det, leaks)
    print(f"\nmatrix {sum(r['pass'] for r in rows)}/{len(rows)}; stability {stab['success_rate']:.0%}; "
          f"determinism {det['distinct_traces']} trace(s); pii hits {len(leaks)}\nwrote {OUT.relative_to(ROOT)}/SUMMARY.md")
    return 0 if all(r["pass"] for r in rows) and not leaks else 1


if __name__ == "__main__":
    sys.exit(main())
